# Generated by Django 5.0.1 on 2024-01-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('call_p', models.CharField(max_length=200)),
                ('sms', models.CharField(max_length=200)),
                ('mb', models.CharField(max_length=200)),
                ('dec', models.CharField(max_length=200)),
                ('discount', models.CharField(max_length=200)),
                ('realPrice', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mobi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('call_p', models.CharField(max_length=200)),
                ('sms', models.CharField(max_length=200)),
                ('mb', models.CharField(max_length=200)),
                ('dec', models.CharField(max_length=200)),
                ('discount', models.CharField(max_length=200)),
                ('realPrice', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ucell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('call_p', models.CharField(max_length=200)),
                ('sms', models.CharField(max_length=200)),
                ('mb', models.CharField(max_length=200)),
                ('dec', models.CharField(max_length=200)),
                ('discount', models.CharField(max_length=200)),
                ('realPrice', models.CharField(max_length=200)),
            ],
        ),
    ]
