# Generated by Django 5.0.1 on 2024-01-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_bee_dec_alter_mobi_dec_alter_ucell_dec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ucell',
            name='sms',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
