# Generated by Django 5.0.1 on 2024-01-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_ucell_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bee',
            name='call_p',
            field=models.CharField(max_length=28),
        ),
        migrations.AlterField(
            model_name='bee',
            name='dec',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
        migrations.AlterField(
            model_name='bee',
            name='discount',
            field=models.CharField(max_length=28),
        ),
        migrations.AlterField(
            model_name='bee',
            name='mb',
            field=models.CharField(max_length=28),
        ),
        migrations.AlterField(
            model_name='bee',
            name='realPrice',
            field=models.CharField(max_length=28),
        ),
        migrations.AlterField(
            model_name='bee',
            name='sms',
            field=models.CharField(max_length=28),
        ),
        migrations.AlterField(
            model_name='bee',
            name='titel',
            field=models.CharField(max_length=28),
        ),
        migrations.AlterField(
            model_name='mobi',
            name='call_p',
            field=models.CharField(max_length=28),
        ),
        migrations.AlterField(
            model_name='mobi',
            name='dec',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
        migrations.AlterField(
            model_name='mobi',
            name='discount',
            field=models.CharField(max_length=28),
        ),
        migrations.AlterField(
            model_name='mobi',
            name='mb',
            field=models.CharField(max_length=28),
        ),
        migrations.AlterField(
            model_name='mobi',
            name='realPrice',
            field=models.CharField(max_length=28),
        ),
        migrations.AlterField(
            model_name='mobi',
            name='sms',
            field=models.CharField(max_length=28),
        ),
        migrations.AlterField(
            model_name='mobi',
            name='titel',
            field=models.CharField(max_length=28),
        ),
        migrations.AlterField(
            model_name='ucell',
            name='call_p',
            field=models.CharField(max_length=28),
        ),
        migrations.AlterField(
            model_name='ucell',
            name='dec',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
        migrations.AlterField(
            model_name='ucell',
            name='discount',
            field=models.CharField(max_length=28),
        ),
        migrations.AlterField(
            model_name='ucell',
            name='mb',
            field=models.CharField(max_length=28),
        ),
        migrations.AlterField(
            model_name='ucell',
            name='realPrice',
            field=models.CharField(max_length=28),
        ),
        migrations.AlterField(
            model_name='ucell',
            name='sms',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
        migrations.AlterField(
            model_name='ucell',
            name='titel',
            field=models.CharField(max_length=28),
        ),
    ]
